export const SECTIONS = [
  "Arts",
  "Automobiles",
  "Books",
  "Business",
  "Fashion",
  "Food",
  "Health",
  "Home",
  "Insider",
  "Magazine",
  "NY Region",
  "Obituaries",
  "Opinion",
  "Politics",
  "Real Estate",
  "Science",
  "Sports",
  "Sunday Review",
  "Technology",
  "Theater",
  "T-Magazine",
  "Travel",
  "Upshot",
  "US",
  "World",
];

export const APPROUTES = [
  "/",
  "/music",
  "/news",
  "/movies",
  "/videos",
  "/music/bookmarked",
  "/news/bookmarked",
  "/movies/bookmarked",
  "/videos/bookmarked",
];

export const LANDING_LINKS = [
  { label: "Music", link: "/music", delay: "500ms" },
  { label: "News", link: "/news", delay: "1000ms" },
  { label: "Movies", link: "/movies", delay: "1500ms" },
  { label: "Videos", link: "/videos", delay: "2000ms" },
];
